// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnXeS8kgyNNKKJTwhUSc5SSdzePKMIMRU',
    appId: '1:1006365343304:web:214a2b703480eba435a27d',
    messagingSenderId: '1006365343304',
    projectId: 'seguradora-1868c',
    authDomain: 'seguradora-1868c.firebaseapp.com',
    storageBucket: 'seguradora-1868c.firebasestorage.app',
    measurementId: 'G-ZCV28W99P6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6UvEhVlaxzCvC90wOhLKPJMDvQhQYnAY',
    appId: '1:1006365343304:android:070f57087a8d693b35a27d',
    messagingSenderId: '1006365343304',
    projectId: 'seguradora-1868c',
    storageBucket: 'seguradora-1868c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb0Z-iQsfAbSlIM0slwpHCYcIp2zbZDn8',
    appId: '1:1006365343304:ios:f31caf1ba034e92035a27d',
    messagingSenderId: '1006365343304',
    projectId: 'seguradora-1868c',
    storageBucket: 'seguradora-1868c.firebasestorage.app',
    iosBundleId: 'com.example.insuranceSeguradora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb0Z-iQsfAbSlIM0slwpHCYcIp2zbZDn8',
    appId: '1:1006365343304:ios:f31caf1ba034e92035a27d',
    messagingSenderId: '1006365343304',
    projectId: 'seguradora-1868c',
    storageBucket: 'seguradora-1868c.firebasestorage.app',
    iosBundleId: 'com.example.insuranceSeguradora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnXeS8kgyNNKKJTwhUSc5SSdzePKMIMRU',
    appId: '1:1006365343304:web:f253484ed0a70e5635a27d',
    messagingSenderId: '1006365343304',
    projectId: 'seguradora-1868c',
    authDomain: 'seguradora-1868c.firebaseapp.com',
    storageBucket: 'seguradora-1868c.firebasestorage.app',
    measurementId: 'G-JDXKWGMM51',
  );
}
